# docker-compose.yml
version: '3'

services:
  app:
    image: python:3.8-slim
    command: bash -c "pip install -r app/requirements.txt && uvicorn app.test:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
